/*
This module contains all the wrapper functions than handle the returned output for all routes.


    ExtractNodeId pulls the row_node_id generated by ag-grid. This tracks which row the data is comming from
    on the client side

    QueryError and QuerrySuccess are wrappers for all get and custom get route return objects

    //this is the final output wrapper for insert/delete/update/upsert. This object gets send
    //to the client. May just send empty arrays for insert, update, upsert, and delete.
    //Maybe check if array first. othewise send empty array

    from (insert,update,delete, function)
    output:
        output: [{data: row1, is_error: bool, error_msg: "", node_id: int/null}]
    from select:
        output: [{row1}, {row2}]
*/

module.exports = {
    ReturnOutput(schema_name, table_name,crud_type,output, is_error=false, err_msg="") {
        output = {
            'schema_name': schema_name,
            'table_name': table_name,
            'crud_type': crud_type,
            'is_error': is_error,
            'error_msg': err_msg,
            'output': []


        }
        return output
    },



}